### ISSUE TITLE
ODT document wrong value printed

### ISSUE THREAD

**Issue by ghost** [opensagres/xdocreport.samples#7]
Hi, i'm following your example, but i've encountered a problem with generated report. The values in table are not populated.
I attach two screen shot:
The first One is template used
![odt_template](https://user-images.githubusercontent.com/4998790/44851399-7c79e000-ac60-11e8-9939-38fb199db910.jpg)
The second One is generated document
![odt_generated_document](https://user-images.githubusercontent.com/4998790/44851417-8865a200-ac60-11e8-8c18-a9eb9f967fa5.jpg)

Thank you in advance for, your response.

**Comment by angelozerr** [comment]
Do you use Input Text Filed in the ODT to write your velocity code?

**Comment by ghost** [comment]
No, i'm write fields by hand, but the fields of list isn't converted. As you see from screenshot, i've tried with special syntax. But with normal syntax is the same.

**Comment by angelozerr** [comment]
You must use input text fields and not type directly your velocity code, because when you save your ODT file, OpenOffice split your velocity code in several XML elements.

Please take time to read https://github.com/opensagres/xdocreport/wiki/ODTReportingQuickStart

**Comment by ghost** [comment]
Thank you, so i need to use the extension that generates xml field.

**Comment by angelozerr** [comment]
No it's not required. you can Insert filed with OpenOffice without this extension.
